import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
// import { useEffect } from 'react';

export const metadata: Metadata = {
  title: 'Chaudhary Matasya Farm',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body className="flex h-full flex-col">{children}</body>
    </html>
  );
};

export default RootLayout;
